//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clicar.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clicar.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access.
        /// </summary>
        internal static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatic.
        /// </summary>
        internal static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand.
        /// </summary>
        internal static string CarBrand {
            get {
                return ResourceManager.GetString("CarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        internal static string CarColor {
            get {
                return ResourceManager.GetString("CarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mileage.
        /// </summary>
        internal static string CarMileage {
            get {
                return ResourceManager.GetString("CarMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model.
        /// </summary>
        internal static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Car evaluation.
        /// </summary>
        internal static string CarRating {
            get {
                return ResourceManager.GetString("CarRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        internal static string CarVersion {
            get {
                return ResourceManager.GetString("CarVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        internal static string CarYear {
            get {
                return ResourceManager.GetString("CarYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer Rut.
        /// </summary>
        internal static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client Name.
        /// </summary>
        internal static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inspection Completed by:.
        /// </summary>
        internal static string CompletedBy {
            get {
                return ResourceManager.GetString("CompletedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conclude.
        /// </summary>
        internal static string Conclude {
            get {
                return ResourceManager.GetString("Conclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currently, the APP is active for the following Branch:.
        /// </summary>
        internal static string ConfigCurrentBranch {
            get {
                return ResourceManager.GetString("ConfigCurrentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select from the list presented the Branch to be configured in the APP..
        /// </summary>
        internal static string ConfigInfoText {
            get {
                return ResourceManager.GetString("ConfigInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a different Branch.
        /// </summary>
        internal static string ConfigPicker {
            get {
                return ResourceManager.GetString("ConfigPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter the car&amp;#39;s VIN number to continue.
        /// </summary>
        internal static string ConfirmInfoText {
            get {
                return ResourceManager.GetString("ConfirmInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please turn on your internet connection.
        /// </summary>
        internal static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current average.
        /// </summary>
        internal static string CurrentMedian {
            get {
                return ResourceManager.GetString("CurrentMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Record.
        /// </summary>
        internal static string CurrentRecord {
            get {
                return ResourceManager.GetString("CurrentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your email here.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Time.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expected time.
        /// </summary>
        internal static string ExpectedTime {
            get {
                return ResourceManager.GetString("ExpectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Final Appraisal.
        /// </summary>
        internal static string FinalAppraisal {
            get {
                return ResourceManager.GetString("FinalAppraisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicate the overall final evaluation of the car.
        /// </summary>
        internal static string FinalAppraisalInfoText {
            get {
                return ResourceManager.GetString("FinalAppraisalInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excellent.
        /// </summary>
        internal static string FiveStars {
            get {
                return ResourceManager.GetString("FiveStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good.
        /// </summary>
        internal static string FourStars {
            get {
                return ResourceManager.GetString("FourStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the Inspection.
        /// </summary>
        internal static string InspectionAccessButton {
            get {
                return ResourceManager.GetString("InspectionAccessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inspection.
        /// </summary>
        internal static string InspectionNo {
            get {
                return ResourceManager.GetString("InspectionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See inspection summary.
        /// </summary>
        internal static string InspectionSummaryBtn {
            get {
                return ResourceManager.GetString("InspectionSummaryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inspection Summary.
        /// </summary>
        internal static string InspectionSummaryTitle {
            get {
                return ResourceManager.GetString("InspectionSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inspection Time.
        /// </summary>
        internal static string InspectionTime {
            get {
                return ResourceManager.GetString("InspectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inspector: .
        /// </summary>
        internal static string Inspector {
            get {
                return ResourceManager.GetString("Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inspector&apos;s Comment.
        /// </summary>
        internal static string InspectorComment {
            get {
                return ResourceManager.GetString("InspectorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locked.
        /// </summary>
        internal static string LockedText {
            get {
                return ResourceManager.GetString("LockedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lock.
        /// </summary>
        internal static string LockText {
            get {
                return ResourceManager.GetString("LockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit the current session?.
        /// </summary>
        internal static string LogoutConfirmText {
            get {
                return ResourceManager.GetString("LogoutConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mechanic.
        /// </summary>
        internal static string Mechanic {
            get {
                return ResourceManager.GetString("Mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad.
        /// </summary>
        internal static string OneStar {
            get {
                return ResourceManager.GetString("OneStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I forgot my Password.
        /// </summary>
        internal static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An email will be sent to reset your password.
        /// </summary>
        internal static string PasswordRecoveryInfo {
            get {
                return ResourceManager.GetString("PasswordRecoveryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign and close using Password.
        /// </summary>
        internal static string PasswordSign {
            get {
                return ResourceManager.GetString("PasswordSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preliminary report.
        /// </summary>
        internal static string PrelimReport {
            get {
                return ResourceManager.GetString("PrelimReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject inspection for:.
        /// </summary>
        internal static string RejectInfoText {
            get {
                return ResourceManager.GetString("RejectInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submit.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grant a general valuation to the car.
        /// </summary>
        internal static string StarRatingInfoText {
            get {
                return ResourceManager.GetString("StarRatingInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start inspection.
        /// </summary>
        internal static string StartInspection {
            get {
                return ResourceManager.GetString("StartInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start time: .
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State: .
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regular.
        /// </summary>
        internal static string ThreeStars {
            get {
                return ResourceManager.GetString("ThreeStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Touch ID Aunthentication.
        /// </summary>
        internal static string TouchIDButton {
            get {
                return ResourceManager.GetString("TouchIDButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign and close using Touch ID.
        /// </summary>
        internal static string TouchIDSign {
            get {
                return ResourceManager.GetString("TouchIDSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transmission.
        /// </summary>
        internal static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceptable.
        /// </summary>
        internal static string TwoStars {
            get {
                return ResourceManager.GetString("TwoStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Name.
        /// </summary>
        internal static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter VIN number.
        /// </summary>
        internal static string VinEntryPlaceholder {
            get {
                return ResourceManager.GetString("VinEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
